---
pid: /home/four_couch/current/tmp/pids/thin.pid
timeout: 5
port: 6000
log: /home/four_couch/current/log/thin.log
max_conns: 1024
require: ['rubygems']

environment: production
max_persistent_conns: 512
servers: 4
daemonize: true
chdir: /home/four_couch/current
